name: seqenv
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.13
  - pip
  - ipykernel
  - ipython
  - numpy
  - biopython
  - matplotlib
  - pysam
  - editdistance
  - bedtools
  - samtools
  - minimap2
  - seqtk
